// Code generated by entc, DO NOT EDIT.

package organization

import (
	"github.com/tmc/pulid"
)

const (
	// Label holds the string label denoting the organization type in the database.
	Label = "organization"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// EdgeCampaigns holds the string denoting the campaigns edge name in mutations.
	EdgeCampaigns = "campaigns"

	// Table holds the table name of the organization in the database.
	Table = "organizations"
	// AccountsTable is the table the holds the accounts relation/edge. The primary key declared below.
	AccountsTable = "organization_accounts"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// CampaignsTable is the table the holds the campaigns relation/edge.
	CampaignsTable = "campaigns"
	// CampaignsInverseTable is the table name for the Campaign entity.
	// It exists in this package in order to avoid circular dependency with the "campaign" package.
	CampaignsInverseTable = "campaigns"
	// CampaignsColumn is the table column denoting the campaigns relation/edge.
	CampaignsColumn = "organization_campaigns"
)

// Columns holds all SQL columns for organization fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// AccountsPrimaryKey and AccountsColumn2 are the table columns denoting the
	// primary key for the accounts relation (M2M).
	AccountsPrimaryKey = []string{"organization_id", "account_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the id field.
	DefaultID func() pulid.ID
)
