// Code generated by entc, DO NOT EDIT.

package account

import (
	"github.com/tmc/pulid"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmailAddress holds the string denoting the email_address field in the database.
	FieldEmailAddress = "email_address"

	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"

	// Table holds the table name of the account in the database.
	Table = "accounts"
	// OrganizationTable is the table the holds the organization relation/edge. The primary key declared below.
	OrganizationTable = "organization_accounts"
	// OrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationInverseTable = "organizations"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldEmailAddress,
}

var (
	// OrganizationPrimaryKey and OrganizationColumn2 are the table columns denoting the
	// primary key for the organization relation (M2M).
	OrganizationPrimaryKey = []string{"organization_id", "account_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the id field.
	DefaultID func() pulid.ID
)
