// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (a *Account) Organization(ctx context.Context) ([]*Organization, error) {
	result, err := a.Edges.OrganizationOrErr()
	if IsNotLoaded(err) {
		result, err = a.QueryOrganization().All(ctx)
	}
	return result, err
}

func (o *Organization) Accounts(ctx context.Context) ([]*Account, error) {
	result, err := o.Edges.AccountsOrErr()
	if IsNotLoaded(err) {
		result, err = o.QueryAccounts().All(ctx)
	}
	return result, err
}

func (o *Organization) Campaigns(ctx context.Context) ([]*Campaign, error) {
	result, err := o.Edges.CampaignsOrErr()
	if IsNotLoaded(err) {
		result, err = o.QueryCampaigns().All(ctx)
	}
	return result, err
}
