// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/tmc/pulid"
	"github.com/tmc/srvgql/ent/account"
	"github.com/tmc/srvgql/ent/campaign"
	"github.com/tmc/srvgql/ent/organization"
	"github.com/tmc/srvgql/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() pulid.ID)
	campaignFields := schema.Campaign{}.Fields()
	_ = campaignFields
	// campaignDescID is the schema descriptor for id field.
	campaignDescID := campaignFields[0].Descriptor()
	// campaign.DefaultID holds the default value on creation for the id field.
	campaign.DefaultID = campaignDescID.Default.(func() pulid.ID)
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescID is the schema descriptor for id field.
	organizationDescID := organizationFields[0].Descriptor()
	// organization.DefaultID holds the default value on creation for the id field.
	organization.DefaultID = organizationDescID.Default.(func() pulid.ID)
}
