// Code generated by entc, DO NOT EDIT.

package campaign

import (
	"github.com/tmc/pulid"
)

const (
	// Label holds the string label denoting the campaign type in the database.
	Label = "campaign"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// Table holds the table name of the campaign in the database.
	Table = "campaigns"
)

// Columns holds all SQL columns for campaign fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Campaign type.
var ForeignKeys = []string{
	"organization_campaigns",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the id field.
	DefaultID func() pulid.ID
)
